version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 1
    container_name: helmet-rss-api
    ports:
      - 8000:8000
    env_file:
      .env
    restart: unless-stopped